[package]
name = "rust_graphql"
version="0.1.0"
edition="2024"

[dependencies]
async-graphql = "6.0.2"
async-graphql-actix-web = "6.0.2"
actix-web = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

